#!/bin/bash -e

. $BRICKS_HOME/builder
. $BRICKS_HOME/execute

mounts() {
  info 'Building workspace'

  pushd /bricks/mounts/volumes/
    echo $BRICKS_MOUNTS_IGNORE | tr ',' '\n' > /tmp/ignore-files
    rsync -a --stats -h --exclude-from /tmp/ignore-files . /opt/workspace
    chown -R builder. /opt/workspace
  popd
}

execute mounts
