#!/bin/bash -le

. $BRICKS_HOME/builder

execute() {
  info 'Building workspace'

  pushd /bricks/mounts/volumes/
    echo $BRICKS_MOUNTS_IGNORE | tr ',' '\n' > /tmp/ignore-files
    rsync -a --stats --exclude-from /tmp/ignore-files . /opt/workspace
    chown -R builder. /opt/workspace
  popd
}

execute
