#!/bin/bash -e

. $BRICKS_HOME/suexec

version() {
    info 'Processing version file'
    pushd /opt/workspace/source
      last_tag=$(git describe --tags --abbrev=0)
      commit=$(git log -1 --pretty=tformat:'%H')
      author=$(git log -1 --pretty=tformat:'%an')
      message=$(git log -1 --pretty=tformat:'%s')
      tag_date=$(git log -1 --pretty=tformat:'%ad')
      
      echo "tag = $last_tag"
      echo "date = $tag_date"
      echo "author = $author"
      echo "commit = $commit"
      echo "message = $message"
      
      generated_version="
        {
           \"tag\": \"$last_tag\",
           \"commit\": \"$commit\",
           \"author\": \"$author\",
           \"message\": \"$message\",
           \"tag_date\": \"$tag_date\"
        }
      "

      echo $generated_version > $BRICKS_VERSION_OUTPUT
    popd
}

suexec version
