#!/bin/bash -e

. $BRICKS_HOME/builder

execute() {
  info 'Starting buildpackage'
  pushd /opt/build/source
    dpkg-buildpackage -b -rfakeroot
  popd

  info 'Moving deb files to volume'
  rm -R /builded/*
  mv /opt/build/*.deb /builded/

  info 'Recreating local debian packages index'
  dpkg-scanpackages /builded/ | gzip > /builded/Packages.gz
}

execute
