#!/bin/bash -e

. $BRICKS_HOME/builder
. $BRICKS_HOME/execute

dotenv() {
  info 'Populating environment variables'

  pushd /bricks/mounts/volumes/source
    echo "From files: $BRICKS_DOTENV_SOURCE_FILES"
    target=/tmp/dotenv
  
    echo $(cat $BRICKS_DOTENV_SOURCE_FILES | \
                   grep -P $(cat $BRICKS_HOME/../dotenv/malignous-regex) | \
                   sed s/export//) > $target

    sed -i 's/^/export /' $target
    . $target
  popd
}

execute dotenv
