#!/bin/bash -le

. $BRICKS_HOME/builder

execute() {
  info 'Vendor project with Bundler'
  pushd /opt/build/source
    gem install bundler --conservative --no-ri --no-rdoc
    bundle install --deployment --without=development:test
  popd
}

execute
