#!/bin/bash -le

info() {
    message=$1;
    echo -e "\n\033[32m${message}\033[0m\n";
}

warning() {
  message=$1;
    echo -e "\033[33m${message}\033[0m\n";
}

show() {
    message=$1;
    echo -e "\033[32m${message}\033[0m";
}

info_bricks() {
    brick=$1;
    message=$(echo "${2//%/%%}");
    printf "\033[32m%8s\033[0m: $message \n" $brick;
}

pushd() {
    command pushd "$@" > /dev/null
}

popd() {
    command popd "$@" > /dev/null
}

export -f info warning info_bricks pushd popd
