#!/bin/bash -le

. $BRICKS_HOME/builder

builder() {
  eval $BRICKY_ENTRYPOINTS
}

builder_source() {
  scripts=$(echo $BRICKY_ENTRYPOINTS | tr " && " "\n")
  cat $scripts > /tmp/builderplan
  grep -v "bin/bash" /tmp/builderplan | more 
}

start() {
  if [[ "$BRICKY_ENTRYPOINTS_SHELL" == "true" ]]
  then
    export -f builder
    export -f builder_source

    info "\n\nType 'builder' to build the project :p"
    info "Type 'builder_source' to see the bricks compilation :p\n\n"
    /bin/bash
  else
    builder
  fi
}

start
