#!/bin/bash -e

. $BRICKS_HOME/builder
export BRICKY_ENTRYPOINTS_SCRIPTS=$(echo $BRICKY_ENTRYPOINTS | tr ',' ' ')

builder() {
    for bricky in $BRICKY_ENTRYPOINTS_SCRIPTS
    do
        . $bricky
        local ret=$?

        if [ $ret -ne 0 ]
        then
            exit $ret
        fi
    done
}

builder_source() {
  cat $BRICKY_ENTRYPOINTS_SCRIPTS > /tmp/builderplan
  grep -v "bin/bash" /tmp/builderplan | more 
}

shell() {
    export -f builder
    export -f builder_source

    show "\n\nType 'builder' to build the project :p"
    show "Type 'builder_source' to see the bricks compilation :p\n\n"
    /bin/bash
}

start() {
  if [[ "$BRICKY_ENTRYPOINTS_SHELL" == "true" ]]
  then
    shell
  else
    builder
  fi
}

start
