# The image locaweb/wheezy-ruby2x contains the following packages:
# locaweb's: ruby, ruby-dev, and bundler packages, and a lots of
# tools inherits from wheezy:development, ex: build-essential.
FROM locaweb/wheezy-ruby2x:development
MAINTAINER bricky

# Small dependencies cheatsheet: 
#
# sqlite: sqlite3, libsqlite3-dev
# nokogiri: libxml2-dev libxslt-dev
# mysql: libmysqlclient-dev
# sqlserver: freetds-dev
# postgresql: libpq-dev

# RUN apt-get update
# RUN apt-get install --no-install-recommends -y --force-yes <your-deps-here>
