#!/bin/bash -l

info() {
  message=$1;
  echo -e "\n\n\033[32m${message}\033[0m";
}

execute() {
  info 'Copying files'
  rsync -a \
  --exclude 'locaweb/containers' \
  --stats /source /opt/build/

  info 'Starting buildpackage'
  pushd /opt/build/source
    dpkg-buildpackage -b -rfakeroot
  popd

  info 'Moving deb files to volume'
  rm -R /builded/*
  mv /opt/build/*.deb /builded/

  info 'Recreating local debian packages index'
  dpkg-scanpackages /builded/ | gzip > /builded/Packages.gz
}

execute
