#!/bin/bash -e

. $BRICKS_HOME/suexec

rails() {
    if [[ $BRICKS_RAILS_ASSETS_PRECOMPILE == "true" ]]
    then
        info 'Rails, assets precompile!'

        pushd /opt/workspace/source
             bundle exec rake assets:clean assets:precompile
        popd
    fi
}

suexec rails
