#!/bin/bash -e

. $BRICKS_HOME/suexec

rails() {
    if [[ $BRICKS_RAILS_ASSETS_PRECOMPILE == "true" ]]
    then
        info 'Rails, assets precompile!'

        pushd /opt/workspace/source
          if [ "$(ls -A public/assets)" ]
          then
              info 'using cached assets :p'
          else
              bundle exec rake assets:precompile
          fi
        popd
    fi
}

suexec rails
